version: '3.3'
services:
  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./.data:/var/lib/mysql
  server:
    build: .
    container_name: web-ctc
    restart: unless-stopped
    ports:
      - 3000:3000
